### ISSUE TITLE
Styling for the Details Summary block

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#250]
Learn has the [Detail Summary block](https://wordpress.org/plugins/details-summary-block/) installed (along with the rest of .org), but there is no frontend styling. This needs to be updated to match the look and feel of Learn.

To test this out, add a 'Details Summary' block to any post and input content. It works (although the editing experience leaves a lot to be desired), but it really doesn't look good at all.

This feature [has been considered for Gutenberg core](https://github.com/WordPress/gutenberg/issues/21584), but that enhancement has stalled for the moment. There are a number of design options on that Gutenberg issue, but this is one that I like the look of for Learn:

<img width="500" alt="83340098-849efd80-a2d4-11ea-9dd4-688bbe79b4f8" src="https://user-images.githubusercontent.com/1543143/137230659-9a071adc-d341-4922-b41c-b17a74a0fbd8.png">

**Comment by hlashbrooke** [comment]
I put together some CSS for this in the Customiser, you can see it in action in this draft: https://learn.wordpress.org/?post_type=lesson&p=9557&preview=true

Here is the CSS that I added:

```css
details {
	border: 1px solid #e7e7e7;
	padding: 0 .9em;
	background: #f7f7f7;
	margin: 1em 0;
}

details::before {
	content: "\025B8";
	margin-right: .2em;
	font-size: 200%;
	display: inline;
	vertical-align: bottom;
	line-height: 1.4;
}

details[open]::before {
	content: "\025BE";
}

details summary {
	display: inline-block;
	font-weight: bold;
	cursor: pointer;
	margin-bottom: .5em;
}
```

It's only in the Customiser and not in the theme since I'm sure someone could do a much better job with this in terms of design and responsiveness, but this is a temporary measure to allow us to start using this block right now.
